# SPDX-FileCopyrightText: 2026 Davide De Rosa
#
# SPDX-License-Identifier: MIT

set(SWIFT_ANDROID_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}")
include("${SWIFT_ANDROID_CMAKE_DIR}/swift-macros.cmake")

if(NOT COMMAND swift_android_resolve_inputs)
macro(swift_android_resolve_inputs)
    if(NOT DEFINED SWIFT_ANDROID_VERSION OR "${SWIFT_ANDROID_VERSION}" STREQUAL "")
        if(DEFINED ENV{SWIFT_ANDROID_VERSION} AND NOT "$ENV{SWIFT_ANDROID_VERSION}" STREQUAL "")
            set(SWIFT_ANDROID_VERSION "$ENV{SWIFT_ANDROID_VERSION}")
        else()
            set(SWIFT_ANDROID_VERSION "6.3.1")
        endif()
    endif()

    if(NOT DEFINED SWIFT_ANDROID_ABI OR "${SWIFT_ANDROID_ABI}" STREQUAL "")
        if(DEFINED CMAKE_ANDROID_ARCH_ABI AND NOT "${CMAKE_ANDROID_ARCH_ABI}" STREQUAL "")
            set(SWIFT_ANDROID_ABI "${CMAKE_ANDROID_ARCH_ABI}")
        elseif(DEFINED ANDROID_ABI AND NOT "${ANDROID_ABI}" STREQUAL "")
            set(SWIFT_ANDROID_ABI "${ANDROID_ABI}")
        elseif(DEFINED ENV{SWIFT_ANDROID_ABI} AND NOT "$ENV{SWIFT_ANDROID_ABI}" STREQUAL "")
            set(SWIFT_ANDROID_ABI "$ENV{SWIFT_ANDROID_ABI}")
        elseif(DEFINED ENV{ANDROID_ABI} AND NOT "$ENV{ANDROID_ABI}" STREQUAL "")
            set(SWIFT_ANDROID_ABI "$ENV{ANDROID_ABI}")
        else()
            message(FATAL_ERROR "Unable to infer Android ABI")
        endif()
    endif()

    if(SWIFT_ANDROID_ABI STREQUAL "arm64-v8a")
        set(_swift_android_arch "aarch64")
    elseif(SWIFT_ANDROID_ABI STREQUAL "x86_64")
        set(_swift_android_arch "x86_64")
    else()
        message(FATAL_ERROR "Unsupported Swift Android ABI: ${SWIFT_ANDROID_ABI}")
    endif()
    if(DEFINED SWIFT_ANDROID_ARCH AND NOT "${SWIFT_ANDROID_ARCH}" STREQUAL "" AND NOT "${SWIFT_ANDROID_ARCH}" STREQUAL "${_swift_android_arch}")
        message(FATAL_ERROR "SWIFT_ANDROID_ARCH=${SWIFT_ANDROID_ARCH} does not match ABI ${SWIFT_ANDROID_ABI}")
    endif()
    set(SWIFT_ANDROID_ARCH "${_swift_android_arch}")

    if(NOT DEFINED SWIFT_ANDROID_API_LEVEL OR "${SWIFT_ANDROID_API_LEVEL}" STREQUAL "")
        if(DEFINED CMAKE_ANDROID_API AND NOT "${CMAKE_ANDROID_API}" STREQUAL "")
            set(SWIFT_ANDROID_API_LEVEL "${CMAKE_ANDROID_API}")
        elseif(DEFINED ANDROID_NATIVE_API_LEVEL AND NOT "${ANDROID_NATIVE_API_LEVEL}" STREQUAL "")
            set(SWIFT_ANDROID_API_LEVEL "${ANDROID_NATIVE_API_LEVEL}")
        elseif(DEFINED ANDROID_PLATFORM AND NOT "${ANDROID_PLATFORM}" STREQUAL "")
            string(REPLACE "android-" "" SWIFT_ANDROID_API_LEVEL "${ANDROID_PLATFORM}")
        elseif(DEFINED CMAKE_SYSTEM_VERSION AND CMAKE_SYSTEM_VERSION MATCHES "^[0-9]+$" AND CMAKE_SYSTEM_VERSION GREATER_EQUAL 28)
            set(SWIFT_ANDROID_API_LEVEL "${CMAKE_SYSTEM_VERSION}")
        elseif(DEFINED ENV{SWIFT_ANDROID_API_LEVEL} AND NOT "$ENV{SWIFT_ANDROID_API_LEVEL}" STREQUAL "")
            set(SWIFT_ANDROID_API_LEVEL "$ENV{SWIFT_ANDROID_API_LEVEL}")
        else()
            message(FATAL_ERROR "Unable to infer Android API level")
        endif()
    endif()
    if(NOT "${SWIFT_ANDROID_API_LEVEL}" MATCHES "^[0-9]+$")
        message(FATAL_ERROR "SWIFT_ANDROID_API_LEVEL must be numeric")
    endif()
    if(SWIFT_ANDROID_API_LEVEL LESS 28)
        message(FATAL_ERROR "SWIFT_ANDROID_API_LEVEL must be >= 28")
    endif()

    if(NOT DEFINED ANDROID_NDK_HOME OR "${ANDROID_NDK_HOME}" STREQUAL "")
        if(DEFINED CMAKE_ANDROID_NDK AND NOT "${CMAKE_ANDROID_NDK}" STREQUAL "")
            set(ANDROID_NDK_HOME "${CMAKE_ANDROID_NDK}")
        elseif(DEFINED ANDROID_NDK AND NOT "${ANDROID_NDK}" STREQUAL "")
            set(ANDROID_NDK_HOME "${ANDROID_NDK}")
        elseif(DEFINED ENV{ANDROID_NDK_HOME} AND NOT "$ENV{ANDROID_NDK_HOME}" STREQUAL "")
            set(ANDROID_NDK_HOME "$ENV{ANDROID_NDK_HOME}")
        else()
            message(FATAL_ERROR "Unable to infer Android NDK path")
        endif()
    endif()
    if(NOT IS_DIRECTORY "${ANDROID_NDK_HOME}")
        message(FATAL_ERROR "ANDROID_NDK_HOME must point to an existing directory: ${ANDROID_NDK_HOME}")
    endif()

    set(SWIFT_ANDROID_SDK "$ENV{HOME}/.swiftpm/swift-sdks/swift-${SWIFT_ANDROID_VERSION}-RELEASE_android.artifactbundle")
    set(SWIFT_ANDROID_TRIPLE "${SWIFT_ANDROID_ARCH}-unknown-linux-android${SWIFT_ANDROID_API_LEVEL}")
    set(SWIFT_RESOURCE_DIR "${SWIFT_ANDROID_SDK}/swift-android/swift-resources/usr/lib/swift_static-${SWIFT_ANDROID_ARCH}")
    if(NOT IS_DIRECTORY "${SWIFT_ANDROID_SDK}")
        message(FATAL_ERROR "SWIFT_ANDROID_SDK must point to an existing directory: ${SWIFT_ANDROID_SDK}")
    endif()
    if(NOT IS_DIRECTORY "${SWIFT_RESOURCE_DIR}")
        message(FATAL_ERROR "SWIFT_RESOURCE_DIR must point to an existing directory: ${SWIFT_RESOURCE_DIR}")
    endif()

    if(NOT DEFINED ANDROID_TOOLCHAIN_ROOT OR "${ANDROID_TOOLCHAIN_ROOT}" STREQUAL "")
        file(GLOB _swift_android_toolchain_roots "${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/*")
        list(LENGTH _swift_android_toolchain_roots _swift_android_toolchain_root_count)
        if(_swift_android_toolchain_root_count GREATER 0)
            list(GET _swift_android_toolchain_roots 0 ANDROID_TOOLCHAIN_ROOT)
        endif()
    endif()
    if(DEFINED ANDROID_TOOLCHAIN_ROOT AND NOT "${ANDROID_TOOLCHAIN_ROOT}" STREQUAL "")
        set(LIBCXX_TRIPLE "${SWIFT_ANDROID_ARCH}-linux-android")
        set(LIBCXX_SHARED_SO "${ANDROID_TOOLCHAIN_ROOT}/sysroot/usr/lib/${LIBCXX_TRIPLE}/libc++_shared.so")
        if(NOT EXISTS "${LIBCXX_SHARED_SO}")
            message(FATAL_ERROR "Unable to find libc++_shared.so: ${LIBCXX_SHARED_SO}")
        endif()
    endif()

    set(SWIFT_ANDROID_CMAKE_ARGS
        -DANDROID_NDK_HOME:PATH=${ANDROID_NDK_HOME}
        -DSWIFT_ANDROID_ABI:STRING=${SWIFT_ANDROID_ABI}
        -DSWIFT_ANDROID_API_LEVEL:STRING=${SWIFT_ANDROID_API_LEVEL}
        -DSWIFT_ANDROID_VERSION:STRING=${SWIFT_ANDROID_VERSION}
        -DCMAKE_TOOLCHAIN_FILE:FILEPATH=${SWIFT_ANDROID_CMAKE_DIR}/swift-android.toolchain.cmake
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY:PATH=<BINARY_DIR>
    )
    if(DEFINED CMAKE_MAKE_PROGRAM AND NOT "${CMAKE_MAKE_PROGRAM}" STREQUAL "")
        list(APPEND SWIFT_ANDROID_CMAKE_ARGS -DCMAKE_MAKE_PROGRAM:FILEPATH=${CMAKE_MAKE_PROGRAM})
    endif()
    if(DEFINED CMAKE_BUILD_TYPE AND NOT "${CMAKE_BUILD_TYPE}" STREQUAL "")
        list(APPEND SWIFT_ANDROID_CMAKE_ARGS -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE})
    endif()
    set(SWIFT_CMAKE_ARGS ${SWIFT_ANDROID_CMAKE_ARGS})
    set(SWIFT_SHARED_LIBRARY_PREFIX "lib")
    set(SWIFT_SHARED_LIBRARY_SUFFIX ".so")
endmacro()
endif()

if(NOT COMMAND swift_android_export_cxx_shared)
macro(swift_android_export_cxx_shared)
    swift_android_resolve_inputs()
    if(NOT DEFINED LIBCXX_SHARED_SO OR "${LIBCXX_SHARED_SO}" STREQUAL "")
        message(FATAL_ERROR "Unable to infer libc++_shared.so path")
    endif()
    set(SWIFT_ANDROID_CXX_SHARED_TARGET SwiftAndroid::cxx_shared)
    if(NOT TARGET ${SWIFT_ANDROID_CXX_SHARED_TARGET})
        add_library(${SWIFT_ANDROID_CXX_SHARED_TARGET} SHARED IMPORTED GLOBAL)
        set_target_properties(${SWIFT_ANDROID_CXX_SHARED_TARGET} PROPERTIES IMPORTED_LOCATION "${LIBCXX_SHARED_SO}")
    endif()
    set(SWIFT_TARGET_INTERFACE_LINK_LIBRARIES "${SWIFT_ANDROID_CXX_SHARED_TARGET}")
endmacro()
endif()

if(NOT SWIFT_ANDROID_ENV_DEFINE_ONLY)
    swift_android_export_cxx_shared()
endif()
